USE [master]
GO
CREATE LOGIN [HotelUser_R_O] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[Hotel], DEFAULT_LANGUAGE=[Deutsch], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Hotel]
GO
CREATE USER [HotelUser_R_O] FOR LOGIN [HotelUser_R_O]
GO
